name: Update tqueis

on:
  schedule:
    - cron: '*/5 * * * *' # Her 5 dakikada bir çalışır
  workflow_dispatch: # Manuel tetikleme butonu

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dosya yazma izni

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install requests urllib3

      - name: Run Script
        run: python tqueis.py # Dosya ismini zonya.py olarak ayarladım

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # Olta klasöründeki m3u8 dosyalarını ekle
          git add olta/*.m3u8
          git commit -m "Zonya Bot: Olta klasörü güncellendi" || exit 0
          git push
